### ISSUE TITLE
JVM: -XX:+UseG1GC -XX:+UseStringDeduplication

### ISSUE THREAD

**Issue by sgwerder** [juditacs/wordcount#88]
Could you try and see if this gives any benefits in performance. Does it even make sense to use G1 GC? @svanoort 
See 13:45ff [Talk / Slides](https://www.infoq.com/presentations/java9-improvements)

**Comment by leventov** [comment]
For this task seems more sensible to allocate less objects (and don't allocate objects which are garbage) and disable GC altogether, see #89

**Comment by sgwerder** [comment]
@leventov Did you test your optimization with the 3.6 GB file? It doesn't complete on my machine: It freezes momentarily and doesn't show any use of the RAM. While as the earlier version completes in 116.5 seconds and goes full monty on my RAM.
Also you have to adapt the run_command.txt.

**Comment by leventov** [comment]
@sgwerder I forgot to commit script updates. Commited now. I didn't test anything (even correct work) except compilation, because it doesn't work on windows.

**Comment by svanoort** [comment]
@sgwerder Confession: I did some tinkering with the GC algorithm, including G1.  Never submitted a PR though, because G1 was slower (to be expected, since it improves latency at the cost of reducing throughput).  StringDeduplication isn't that different from our hashtable use here -- we don't have multiple references to identical strings.  

In Java 9 G1 is supposed to have some significant improvements though, so might be faster.
